### ISSUE TITLE
Add comprehensive documentation (using Sphinx)

### ISSUE THREAD

**Issue by brylie** [facebookresearch/Horizon#56]
Please add comprehensive documentation, including:

- project overview
- quickstart
- one or more tutorials
- API reference

By way of example, the [scikit-learn docs](http://scikit-learn.org/stable/documentation.html) are superbe. Also [PyTorch](https://pytorch.org/docs/stable/index.html) and [Keras](https://keras.io/) have useful documentation.

**Comment by brylie** [comment]
@MisterTea thanks for updating the wiki :smiley:  

In my experience, the GitHub wiki pages are somewhat like a scratch-pad for quickly jotting down brief introductory texts. Often though, projects will create more comprehensive documentation, using tools like [Sphinx](http://www.sphinx-doc.org/en/master/), which includes in-depth information like:

- project overview/architecture
- quickstart guide
- one or more tutorials on specfic use cases
- comprehensive API reference, so that developers don't need to guess

May I propose we adopt Sphinx as the documentation tool for this project, possibly with [markdown syntax support](http://www.sphinx-doc.org/en/master/usage/markdown.html) if desired? I am available to assist with this task.

**Comment by MisterTea** [comment]
@brylie I think there are two separate streams of thought here:

First, there is the medium: we are using the README.md to link to other md files and use the GitHub source viewer to provide the platform.  I'm not opposed to having a separate website, but using the md files has some nice advantages: (1) it compels people to contribute since they are one click away from making changes, and (2) we will need information in the README anyways, so it deduplicates some work.  But the point of the documentation is so serve people who are using the platform, so if there is demand for a separate website, this is fine.

Then there is the content itself.  From my perspective, we have a clear tutorial in the usage page.  I'm not sure what the difference is between a tutorial and a quickstart guide, so it would be great to get clarity there.  We definitely can use help with the architecture and API sections.

**Comment by brylie** [comment]
> I'm not sure what the difference is between a tutorial and a quickstart guide, so it would be great to get clarity there.

Yeah, tutorials and quick start are quite similar, but tutorials tend to be a bit more in-depth. 

Here are some examples of scikit-learn tutorials:
- Quick start tutorial: https://scikit-learn.org/stable/tutorial/basic/tutorial.html
- Various additional tutorials: https://scikit-learn.org/stable/tutorial/index.html

Overall, note how the scikit-learn documentation is organized:
https://scikit-learn.org/stable/documentation.html

I am not suggesting that Horizon have such extensive documentation immediately, but that the project dedicate some focused efforts on documentation (I am also volunteering to help).

**Comment by MisterTea** [comment]
Closing.  If someone wants to integrate sphinx, a PR would be great.

**Comment by MisterTea** [comment]
Doc up here (on the gh-pages branch): https://facebookresearch.github.io/Horizon/
