### ISSUE TITLE
Mistake in usage.md

### ISSUE THREAD

**Issue by MariusDanner** [facebookresearch/Horizon#86]
Hi, I am currently trying to familiarize myself with Horizon and I noticed that the usage.md doesn't add up completely. In Part 2 after running 
```
/usr/local/spark/bin/spark-submit \
  --class com.facebook.spark.rl.Preprocessor preprocessing/target/rl-preprocessing-1.1.jar \
  "`cat ml/rl/workflow/sample_configs/discrete_action/timeline.json`"
```

In the next steps it is always referred to `cartpole_discrete_timeline` but this directory doesn't exist. Do you mean `cartpole_discrete_training`? I checked out the master branch on commit 6a5cd1591d4ad610197095d00b96a441aa61a0ac

**Comment by jbkoh** [comment]
I experience the same issue. It looks like the documentation has been drifted. I tried to move the files ``cartpole_discrete_training/part_xxx.json`` and ``cartpole_discrete_eval/part_yyy.json`` into ``training_data/cartpole_discrete_training.json`` and ``training_data/cartpole_discrete_test.json`` each. It worked through the tutorial until the last step. The tensorboard did not show anything, but said ``No dashboards are active for the current data set.``

**Comment by gterziysky** [comment]
@jbkoh is right.

The reason is that the output directory (i.e. [outputTableName](https://github.com/facebookresearch/Horizon/blob/6a5cd1591d4ad610197095d00b96a441aa61a0ac/ml/rl/workflow/sample_configs/discrete_action/timeline.json#L8) param) in the [timeline.json](https://github.com/facebookresearch/Horizon/blob/6a5cd1591d4ad610197095d00b96a441aa61a0ac/ml/rl/workflow/sample_configs/discrete_action/timeline.json) config file changed from cartpole_discrete_timeline to cartpole_discrete_timeline.

**Comment by econti** [comment]
Thanks for letting us know! Please send a PR to fix if you don't mind, else we will get to it soon!

**Comment by MisterTea** [comment]
This should be fixed in https://github.com/facebookresearch/Horizon/commit/90597cd8f5daf64f217138ef745b9853f0409e34 .  Please let me know if it isn't.
