### ISSUE TITLE
request for more detailed documentation 

### ISSUE THREAD

**Issue by chanansh** [facebookresearch/Horizon#98]
documentation is very short. It's not clear how to run this on my dataset.
Moreover, what if my rewards are delayed and accumulative across time for each action, so at time t'>t I get reward events of action at time t.

**Comment by econti** [comment]
Hey @chanansh  - hav you checked out our [usage](https://github.com/facebookresearch/Horizon/blob/master/docs/usage.md) guide? Having delayed rewards is perfectly fine and is part of what makes a problem a reinforcement learning problem. RL algorithms are mean to handle difficult credit assignment as the one you describe. When you receive a reward at a timestep `t` it is fine and expected that it may be due to actions taken in previous timesteps.

**Comment by chanansh** [comment]
In my case the assignment is trivial. I know which action caused which
reward .

**Comment by econti** [comment]
Got it. In that case it sounds like the reward is delayed, but independent of subsequent actions taken between time t and t'. You would just assign the delayed reward to time t (the timestep in which the action was taken that lead to this delayed reward).

**Comment by chanansh** [comment]
Assignment is not fair as it is not causal (unknown at time t) so that
simulation is not fair (agent cannot use it for learning).

**Comment by MisterTea** [comment]
@chanansh The policy that you learn 

> pi(s) -> a 

is not a function of the reward, so it's perfectly fair to use anything as you want in the reward, because you don't need it when scoring the model.  Closing but feel free to re-open if there's follow-up.
